{
	"version": 1741161809,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/rickvsmortybg-sheet0.png",
		"images/meme-sheet0.png",
		"images/meme-sheet1.png",
		"images/platform-sheet0.png",
		"images/ball-sheet0.png",
		"images/wall-sheet0.png",
		"images/tile-sheet0.png",
		"images/tile-sheet1.png",
		"images/particles.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/bounce.m4a",
		"media/bounce.ogg",
		"media/brick break.m4a",
		"media/brick break.ogg",
		"media/win.m4a",
		"media/win.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/bg.m4a",
		"media/bg.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}